--vim.opt.guicursor = ""
vim.g.mapleader = " "
vim.api.nvim_set_option("guicursor", "a:block")
vim.api.nvim_set_option("hlsearch", false)
vim.api.nvim_set_option("relativenumber", true)
vim.api.nvim_set_option("number", true)
vim.api.nvim_set_option("mouse", "a")
vim.api.nvim_set_option("breakindent", true)
vim.api.nvim_set_option("undofile", true)
vim.api.nvim_set_option("ignorecase", true)
vim.api.nvim_set_option("smartcase", true)
vim.api.nvim_set_option("updatetime", 50)
vim.api.nvim_set_option("signcolumn", "yes")
vim.api.nvim_set_option("guicursor", "")
vim.api.nvim_set_option("wrap", false)
vim.api.nvim_set_option("scrolloff", 8)
vim.api.nvim_set_option("tabstop", 4)
vim.api.nvim_set_option("softtabstop", 4)
vim.api.nvim_set_option("shiftwidth", 4)
vim.api.nvim_set_option("expandtab", true)
vim.api.nvim_set_option("completeopt", "menuone,noselect")
vim.api.nvim_set_option("termguicolors", true)
vim.api.nvim_set_option("colorcolumn", "80")
vim.api.nvim_set_option("clipboard", "unnamedplus")
